export type Article = {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  date: string;
  timestamp: string;
  last_updatedd: string;
  thumbnail: string;
  image: string;
  reading_time: string;
  category: string;
  sub_category: string;
  tags: string[];
  difficulty: string;
  author_name: string;
  author_avatar: string;
  seo_meta_title: string;
  seo_meta_description: string;
  status: string;
  is_featured: boolean;
  featured_order: number;
  views: number;
  likes: number;
  comments_count: number;
  seo_meta_keywords: string;
};
