export type Article = {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  date: Date;
  timestamp: Date;
  last_updated: Date;
  thumbnail: string;
  image: string;
  reading_time: number;
  category: string;
  sub_category: string;
  tags: string[];
  difficulty: "beginner" | "intermediate" | "advanced";
  author_name: string;
  author_avatar: string;
  seo_meta_title: string;
  seo_meta_description: string;
  seo_meta_keywords: string;
  status: "draft" | "published" | "archived";
  is_featured: boolean;
  featured_order: number;
  views: number;
  likes: number;
  comments_count: number;
};
